Add missing permission.
> Status: Downloaded newer image for ghcr.io/pypa/gh-action-pypi-publish:release-v1
> Error: Trusted publishing exchange failure:
> OpenID Connect token retrieval failed: GitHub: missing or insufficient OIDC token permissions, the ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset